### ISSUE TITLE
gz-gui test segfault with qt-main 5.15.8

### ISSUE THREAD

**Issue by traversaro** [conda-forge/gz-gui-feedstock#9]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am experiencing segfaults in https://github.com/gazebosim/gz-gui/blob/gz-gui7_7.1.0/src/MainWindow.cc#L109 when using qt-main 5.15.8 . If I install qt-main 5.15.3 (the same version used in apt with Ubuntu 22.04) everything works fine.

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by traversaro** [comment]
I tried more in depth, and qt-main 5.14.4 works, while 5.15.6 fails (5.15.5 is not packaged in conda-forge).

**Comment by traversaro** [comment]
> I tried more in depth, and qt-main 5.15.6 *_6 works, while 5.15.8 *_6 fails (5.15.7 is not packaged in conda-forge, and the build was not reset in the update from 5.15.6 to 5.15.8).

The corresponding PR is https://github.com/conda-forge/qt-main-feedstock/pull/113, but I can't find anything strange there.

**Comment by traversaro** [comment]
I am able to avoid the segfault by commenting almost all the main.qml file:
~~~
diff --git a/include/gz/gui/qml/Main.qml b/include/gz/gui/qml/Main.qml
index 132bac2b..d0d450e4 100644
--- a/include/gz/gui/qml/Main.qml
+++ b/include/gz/gui/qml/Main.qml
@@ -159,6 +159,7 @@ ApplicationWindow
   /**
    * Top toolbar
    */
+   /*
   header: ToolBar {
     Material.background: toolBarColor
     Material.foreground: Material.foreground
@@ -234,28 +235,31 @@ ApplicationWindow
         }
       }
     }
-  }
+  }*/
 
   /**
    * Background
    */
+  /*
   GzSplit {
     anchors.fill: parent
-  }
+  }*/
 
   /**
    * Left menu
    */
+   /*
   SideDrawer {
     id: drawer
     interactive: MainWindow.showDrawer
     width: Math.min(window.width * 0.3, 500)
     height: window.height
-  }
+  }*/
 
   /**
    * About dialog
    */
+   /*
   Dialog {
     id: aboutDialog
     modal: true
@@ -277,17 +281,18 @@ ApplicationWindow
         font.pixelSize: 12
       }
     }
-  }
+  }*/
 
   /**
    * Style dialog
    */
+   /*
   StyleDialog {
     id: styleDialog
     x: (window.width - width) / 2
     y: window.height / 6
     width: Math.min(window.width, window.height) * 0.5
-  }
+  }*/
 
   /**
    * Load file dialog
@@ -325,10 +330,10 @@ ApplicationWindow
       MainWindow.OnSaveConfigAs(selected);
     }
   }
-
+  /*
   GzSnackBar {
     id: notificationDialog
-  }
+  }*/
 
   Timer {
     id: timer
@@ -337,6 +342,7 @@ ApplicationWindow
   /**
    *  Confirmation dialog on close button
    */
+  /*
   Dialog {
     id: confirmationDialogOnExit
     title: (dialogOnExitText ? dialogOnExitText : "Do you really want to exit?")
@@ -383,5 +389,5 @@ ApplicationWindow
           }
         }
       }
-  }
+  }*/
 }

~~~

However, I can't find any specific logic for when it segfaults  vs when it does not.

**Comment by traversaro** [comment]
I was able to create a Minimum Reproducible Example for this problem, that does not uses gz-gui at all: https://gist.github.com/traversaro/43eecd78b6580e54c978c7fe56048518 . With this, I can more easily study the problem and open an issue in qt-main-feedstock.

**Comment by Tobias-Fischer** [comment]
Looks like https://github.com/conda-forge/qt-feedstock/issues/241

**Comment by traversaro** [comment]
Good catch, thanks! I did checked qt-main existing issues but not qt ones.

**Comment by Tobias-Fischer** [comment]
Do we still have this issue?

**Comment by traversaro** [comment]
Fixed by https://github.com/conda-forge/qt-main-feedstock/pull/155 .
